//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalletHelper.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using WalletHelper.Entity;
    
    public partial class WalletHelperContext : DbContext
    {
        public WalletHelperContext()
            : base("WalletHelper.Database")
        {
            //Database.SetInitializer<WalletHelperContext>(new DropCreateDatabaseIfModelChanges<WalletHelperContext>());
        }
    
        public virtual DbSet<Capture> Capture { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Geolocation> Geolocation { get; set; }
        public virtual DbSet<Hashtag> Hashtag { get; set; }
        public virtual DbSet<NotificationType> NotificationType { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<PaymentMethodDetail> PaymentMethodDetail { get; set; }
        public virtual DbSet<Recording> Recording { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<ScheduledPayment> ScheduledPayment { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserNotification> UserNotification { get; set; }
        public virtual DbSet<UserReference> UserReference { get; set; }
        public virtual DbSet<UserType> UserType { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethod { get; set; }
        public virtual DbSet<PeriodType> PeriodType { get; set; }
    }
}
