//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalletHelper.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Geolocation
    {
        public int Id { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
        public string LocationName { get; set; }
        public int Payment_Id { get; set; }
    
        public virtual Payment Payment { get; set; }
    }
}
