//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalletHelper.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduledPayment
    {
        public ScheduledPayment()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Value { get; set; }
        public int PaymentType { get; set; }
        public int Schedule_Id { get; set; }
    
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
