//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalletHelper.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Hashtags = new HashSet<Hashtag>();
            this.Payments = new HashSet<Payment>();
            this.PaymentMethodDetails = new HashSet<PaymentMethodDetail>();
            this.Schedules = new HashSet<Schedule>();
            this.UserNotifications = new HashSet<UserNotification>();
            this.ReferencedUsers = new HashSet<UserReference>();
            this.SponsorUsers = new HashSet<UserReference>();
        }
    
        public int Id { get; set; }
        public string AspNetUser_Id { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public System.DateTime BirthDate { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> LastSessionDate { get; set; }
        public int LastDeviceUsed_Id { get; set; }
        public int City_Id { get; set; }
        public int Status_Id { get; set; }
        public int Type_Id { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<Hashtag> Hashtags { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<PaymentMethodDetail> PaymentMethodDetails { get; set; }
        public virtual ICollection<Schedule> Schedules { get; set; }
        public virtual Status Status { get; set; }
        public virtual UserType UserType { get; set; }
        public virtual ICollection<UserNotification> UserNotifications { get; set; }
        public virtual ICollection<UserReference> ReferencedUsers { get; set; }
        public virtual ICollection<UserReference> SponsorUsers { get; set; }
    }
}
