//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalletHelper.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public Payment()
        {
            this.Capture = new HashSet<Capture>();
            this.Geolocation = new HashSet<Geolocation>();
            this.Recording = new HashSet<Recording>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public byte[] Description { get; set; }
        public decimal Value { get; set; }
        public bool IsScheduled { get; set; }
        public int PaymentType { get; set; }
        public int ScheduledPayment_Id { get; set; }
        public int PaymentMethodDetail_Id { get; set; }
        public int User_Id { get; set; }
        public int Status_Id { get; set; }
    
        public virtual ICollection<Capture> Capture { get; set; }
        public virtual ICollection<Geolocation> Geolocation { get; set; }
        public virtual PaymentMethodDetail PaymentMethodDetail { get; set; }
        public virtual ScheduledPayment ScheduledPayment { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Recording> Recording { get; set; }
    }
}
