//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalletHelper.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserNotification
    {
        public int Id { get; set; }
        public int DayHour { get; set; }
        public int Status { get; set; }
        public int NotificationType_Id { get; set; }
        public int User_Id { get; set; }
    
        public virtual NotificationType NotificationType { get; set; }
        public virtual User User { get; set; }
    }
}
