//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalletHelper.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Hashtag = new HashSet<Hashtag>();
            this.Payment = new HashSet<Payment>();
            this.PaymentMethodDetail = new HashSet<PaymentMethodDetail>();
            this.Schedule = new HashSet<Schedule>();
            this.UserNotification = new HashSet<UserNotification>();
        }
    
        public int Id { get; set; }
        public string AspNetUser_Id { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public System.DateTime BirthDate { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> LastSessionDate { get; set; }
        public int LastDeviceUsed_Id { get; set; }
        public int City_Id { get; set; }
        public int Status_Id { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<Hashtag> Hashtag { get; set; }
        public virtual ICollection<Payment> Payment { get; set; }
        public virtual ICollection<PaymentMethodDetail> PaymentMethodDetail { get; set; }
        public virtual ICollection<Schedule> Schedule { get; set; }
        public virtual Status Status { get; set; }
        public virtual ICollection<UserNotification> UserNotification { get; set; }
    }
}
